In [315]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [316]:
df = pd.read_csv('../dataset/original_datset.csv')

In [317]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,"""₹314.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

In [318]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,"""₹314.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

In [319]:
df.shape

(2, 24)

In [320]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              2 non-null      int64
 1   title                   2 non-null      object
 2   product_description     2 non-null      object
 3   rating                  2 non-null      float64
 4   ratings_count           2 non-null      int64
 5   initial_price           2 non-null      float64
 6   discount                2 non-null      float64
 7   final_price             2 non-null      object
 8   currency                2 non-null      object
 9   images                  2 non-null      object
 10  delivery_options        2 non-null      object
 11  product_details         2 non-null      object
 12  breadcrumbs             2 non-null      object
 13  product_specifications  2 non-null      object
 14  amount_of_stars         2 non-null      object
 15  what_customers_said     0 non-null      float64
 16  seller_name             2 non-null      object
 17  sizes                   2 non-null      object
 18  videos                  0 non-null      float64
 19  seller_information      2 non-null      object
 20  variations              0 non-null      float64
 21  best_offer              2 non-null      object
 22  more_offers             2 non-null      object
 23  category                2 non-null      object
dtypes: float64(6), int64(2), object(16)
memory usage: 516.0+ bytes

In [321]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [322]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said       float64
seller_name                object
sizes                      object
videos                    float64
seller_information         object
variations                float64
best_offer                 object
more_offers                object
category                   object
dtype: object

In [323]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       2
seller_name               0
sizes                     0
videos                    2
seller_information        0
variations                2
best_offer                0
more_offers               0
category                  0
dtype: int64

In [324]:
df.fillna(method='ffill', inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2132\3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [325]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       2
seller_name               0
sizes                     0
videos                    2
seller_information        0
variations                2
best_offer                0
more_offers               0
category                  0
dtype: int64

In [326]:
df.drop_duplicates(subset=['product_id'])

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,"""₹314.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

In [327]:
df.duplicated().sum()

np.int64(0)

In [328]:
df.shape

(2, 24)

In [329]:
selected_col=df[['final_price','initial_price','rating','title']]
selected_col.head()

  final_price  initial_price  rating          title
0   "₹719.00"         1999.0     4.1      Cutiekins
1   "₹314.00"          449.0     4.5  Nottie Planet

In [330]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,"""₹314.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

In [331]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

df['final_price'] = df['final_price'].replace('[₹,"]', '', regex=True)

df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

In [332]:
print(df[['rating', 'final_price']].dtypes)

rating         float64
final_price    float64
dtype: object

In [333]:
selected_rows1 = df[(df['rating'] > 3.0) ]

selected_rows1.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,719.0,INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,314.0,INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

In [334]:
selected_rows2=df[df['final_price'] < 1000]
selected_rows2.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,719.0,INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,314.0,INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

In [335]:
df['quantity']=np.random.randint(2,5,size=len(df))

In [336]:
df.shape

(2, 25)

In [337]:
df['total amount']=df['final_price']*df['quantity']

In [338]:
df.shape

(2, 26)

In [339]:
df[['total amount','final_price','quantity']].head()

   total amount  final_price  quantity
0        2876.0        719.0         4
1        1256.0        314.0         4

In [340]:
df.to_csv('final_cleaned_dataset.csv',index=False)

In [341]:
pd.read_csv('final_cleaned_dataset.csv').head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total amount
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,719.0,INR,http://assets.myntassets.com/assets/images/167...,...,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set,4,2876.0
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,314.0,INR,http://assets.myntassets.com/assets/images/218...,...,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set,4,1256.0